# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
os: 
- linux
- osx
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages


r_packages:
  - xml2

r_github_packages:
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library(covr); codecov()'
